CREATE DATABASE QLCF
USE QLCF
GO
drop database QLCF
-- Tạo table
CREATE TABLE USERROLE
(
	IdRole INT IDENTITY(1,1) NOT NULL,
	DisplayName nvarchar(100) 
)
CREATE TABLE ACCOUNT
(
	ID INT IDENTITY(1,1) NOT NULL,
	TK NVARCHAR(100) NOT NULL,
	MK NVARCHAR(100),
	IdRole INT NOT NULL
)
CREATE TABLE MON
(
	MaM CHAR(4) NOT NULL,
	TenMon NVARCHAR(100),
	DonGia SMALLMONEY,
	MaLoai INT
)
CREATE TABLE PHANLOAI
(
	MaLoai INT IDENTITY(1,1) NOT NULL,
	TenLoai NVARCHAR(100)
)
CREATE TABLE HOADON 
(
	MaHD INT IDENTITY(1,1) NOT NULL,
	NgXuat DATE,
	TongGia MONEY,
	MaTB INT
)
CREATE TABLE CTHD
(
	MaHD INT IDENTITY(1,1) NOT NULL,
	MaM CHAR(4) NOT NULL,
	SL INT
)
CREATE TABLE THEBAN
(
	MaTB INT IDENTITY(1,1) NOT NULL,
	TinhTrang INT default 0 --0 Trống||1 Có người
)
--Thiết lập khóa chính
ALTER TABLE USERROLE 
ADD CONSTRAINT PK_USERROLE PRIMARY KEY(IdRole)

ALTER TABLE ACCOUNT 
ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY(ID)

ALTER TABLE MON
ADD CONSTRAINT PK_MON PRIMARY KEY(MaM)

ALTER TABLE PHANLOAI
ADD CONSTRAINT PK_PHANLOAI PRIMARY KEY (MaLoai)

ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON PRIMARY KEY (MaHD)

ALTER TABLE CTHD
ADD CONSTRAINT PK_CTHD PRIMARY KEY (MaHD,MaM)

ALTER TABLE THEBAN
ADD CONSTRAINT PK_THEBAN PRIMARY KEY (MaTB)

--Thiết lập khóa ngoại
ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_USERROLE FOREIGN KEY (IdRole) REFERENCES USERROLE(IdRole)

ALTER TABLE MON
ADD CONSTRAINT FK_MON_PHANLOAI FOREIGN KEY (MaLoai) REFERENCES PHANLOAI(MaLoai)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_THEBAN FOREIGN KEY (MaTB) REFERENCES THEBAN(MaTB)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_MON FOREIGN KEY (MaM) REFERENCES MON(MaM)

--INSERT
INSERT INTO USERROLE(DisplayName)
VALUES ('admin'),
		('staff')
select *from USERROLE

INSERT INTO ACCOUNT(TK,MK,IdRole)
VALUES ('admin','123',1)
select*from ACCOUNT

INSERT INTO PHANLOAI(TenLoai)
VALUES (N'CÀ PHÊ VIỆT NAM'),
		(N'CÀ PHÊ MÁY'),
		(N'ĐÁ XAY'),
		(N'TRÀ TRÁI CÂY'),
		(N'TRÀ SỮA MACCHIATO')
select*from PHANLOAI

INSERT INTO MON(MaM,TenMon,DonGia,MaLoai)
VALUES (1001,N'Cà Phê Đen',20000, 1),
		(1002,N'Cà Phê Sữa',25000, 1),
		(1003,N'Bạc xỉu',29000, 1),

		(2001,N'Americano',39000, 2),
		(2002,N'Cappucino',39000, 2),
		(2003,N'Caramel Macchiato',39000, 2),
		(2004,N'Espresso',39000, 2),
		(2005,N'Latte',39000, 2),
		(2006,N'Mocha',39000, 2),

		(3001,N'Phúc Bồn Tử',32000, 3),
		(3002,N'Sữa Tươi Macchiato',32000, 3),
		(3003,N'Sữa tươi',32000, 3),
		(3004,N'Truyền thống',32000, 3),

		(4001,N'Trà Đào Cam Sả',30000, 4),
		(4002,N'Trà Hạt Sen',30000, 4),
		(4003,N'Trà phúc bồn tử',30000, 4),
		(4004,N'Trà vải',30000, 4),

		(5001,N'Trà đen Macchiato',35000, 5),
		(5002,N'Trà lài Macchiato',35000, 5),
		(5003,N'Matcha Macchiato',35000, 5),
		(5004,N'Trà sữa trân châu',35000, 5),
		(5005,N'Trà xoài Macchiato',35000, 5)
select*from MON
